# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PiholeTui < Formula
  desc "TUI for managing Pi-hole remotely"
  homepage "https://github.com/rodrigodealer/pihole-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.1.0/pihole-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "4b80141ce57a26f3ad639dd229723ae3d5a511d0aac1f7b361ebfaccb266a2b7"

      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.1.0/pihole-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "f47bca440422a703551e9bacd7aaccd1b67d59cd070722a1d9e707f3f7349249"

      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.1.0/pihole-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "8cec9752c16d9d8ab5d1814f7e2deeb8783dd84d9699a0a01577c23ba2603eb3"
      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.1.0/pihole-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "1f1b1c0b9c5b94a2127a71d5aee9c65a07858842e59bf0390e862ec1e947da2d"
      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
  end

  test do
    system "#{bin}/pihole-tui", "--version"
  end
end
