# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PiholeTui < Formula
  desc "TUI for managing Pi-hole remotely"
  homepage "https://github.com/rodrigodealer/pihole-tui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.2.0/pihole-tui_0.2.0_darwin_amd64.tar.gz"
      sha256 "d160cbdf23db53d6da578a55ba6aaf2b422728d3cee96629334bbdc66a8c4914"

      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.2.0/pihole-tui_0.2.0_darwin_arm64.tar.gz"
      sha256 "cdfcd3ce88d63404ea8ef31f619e962abbf9749ad5bda328b1ef0510f23e0416"

      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.2.0/pihole-tui_0.2.0_linux_amd64.tar.gz"
      sha256 "3d970f321cd20c12e2ace3373fb628a9b4cdbee2c7ee39989f48b469069b9ba1"
      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rodrigodealer/pihole-tui/releases/download/v0.2.0/pihole-tui_0.2.0_linux_arm64.tar.gz"
      sha256 "b9ebef4ff93cd3e1c76631d59abb311b4eed374ce6a06917722b44f58315e772"
      define_method(:install) do
        bin.install "pihole-tui"
      end
    end
  end

  test do
    system "#{bin}/pihole-tui", "--version"
  end
end
